# Generated by Django 5.1.2 on 2024-10-16 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_app', '0002_modulo_remove_leccion_numero_alter_leccion_modulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='titulo',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='leccion',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coding_app.modulo'),
        ),
    ]
