# Generated by Django 5.1.2 on 2024-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_app', '0003_rename_titulo_modulo_nombre_leccion_orden_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='modulo',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
