# Generated by Django 5.1.2 on 2024-10-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_app', '0004_rename_nombre_modulo_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='modulo',
            name='numero',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
