# Generated by Django 5.1.2 on 2024-10-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_app', '0005_remove_modulo_orden_remove_modulo_titulo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['modulo__numero', 'orden']},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['numero']},
        ),
        migrations.AlterField(
            model_name='leccion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='coding_app.modulo'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='orden',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(default='Default Module Name', max_length=100),
        ),
    ]
